company = ["Exxon Mobil",
    "Wal-Mart",
    "Chevron",
    "ConocoPhillips",
    "General Electric",
    "General Motors",
    "Ford Motor",
    "AT&T",
    "Hewlett-Packard",
    "Valero Energy",
    "Bank of America",
    "Citigroup",
    "Berkshire Hathaway",
    "International Business Machines",
    "McKesson",
    "J.P. Morgan Chase",
    "Verizon Communications",
    "Cardinal Health",
    "CVS Caremark",
    "Procter & Gamble",
    "UnitedHealth Group",
    "Kroger",
    "Marathon Oil",
    "Costco Wholesale",
    "Home Depot",
    "AmerisourceBergen",
    "Archer Daniels Midland",
    "Target",
    "Johnson & Johnson",
    "Morgan Stanley",
    "State Farm Insurance",
    "WellPoint",
    "Dell",
    "Boeing",
    "Microsoft",
    "Walgreen",
    "United Technologies",
    "Dow Chemical",
    "MetLife",
    "Goldman Sachs Group",
    "Sunoco",
    "Wells Fargo",
    "United Parcel Service",
    "Caterpillar",
    "Medco Health Solutions",
    "Pfizer",
    "Lowe's",
    "Time Warner",
    "Sears Holdings",
    "Safeway",
    "Supervalu",
    "PepsiCo",
    "Kraft Foods",
    "Lockheed Martin",
    "Hess",
    "Best Buy",
    "Cisco Systems",
    "Johnson Controls",
    "FedEx",
    "Walt Disney",
    "Intel",
    "Sysco",
    "Honeywell International",
    "Sprint Nextel",
    "Enterprise GP Holdings",
    "GMAC",
    "Ingram Micro",
    "Comcast",
    "Northrop Grumman",
    "3M",
    "Altria Group",
    "Amazon.com",
    "American Express",
    "American International Group",
    "Amgen",
    "Apple",
    "Avnet",
    "Bristol-Myers Squibb",
    "Capital One Financial",
    "Cisco Systems",
    "Coca-Cola",
    "Colgate-Palmolive",
    "Computer Sciences",
    "Danaher",
    "DIRECTV",
    "Dow Chemical",
    "Duke Energy",
    "Eli Lilly",
    "Emerson Electric",
    "Express Scripts",
    "Fannie Mae",
    "Fluor",
    "Freddie Mac",
    "General Dynamics",
    "Gilead Sciences",
    "Google",
    "Halliburton",
    "Hartford Financial Services",
    "HCA",
    "Humana"];